services:
  app1: &app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    hostname: app1
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - LOG_LEVEL=debug
    expose:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.3G'

  app2:
    <<: *app
    hostname: app2

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:3000"
    depends_on:
      - app1
      - app2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.2G'
